# Makefile automatically generated by ghdl
# Version: GHDL 0.36 (v0.36) [Dunoon edition] - GCC back-end code generator
# Command used to generate this makefile:
# ghdl --gen-makefile lan9254esctb

CROSS=arm-linux-gnueabi-
GHDL=$(CROSS)ghdl
CXX=$(CROSS)g++
GHDLFLAGS=
SIITOOL=../master/siitool/siitool


PROG=lan9254escrun
OBJS=Lan9254Pkg.o Lan9254ESCPkg.o Lan9254ESC.o Lan9254Hbi.o Lan9254HbiSoft.o readWriteSim.o EEEmulPkg.o EEPROMContentPkg.o RxPDOSoft.o

TOPS=Lan9254ESCTb.o Lan9254ESCrun.o 

# Default target
all: $(PROG)

# Elaboration target
$(PROG): $(OBJS) $(TOPS)
	$(GHDL) -e -Wl,readWriteSim.o $(GHDLFLAGS) $@

readWriteSim.o: readWriteSim.c
	$(CXX) -c -o $@ $^ -Wall

# Run target
run: $(PROG)
	$(GHDL) -r $(PROG) $(GHDLRUNFLAGS)

EEPROMContentPkg.vhd: eeprom.bin gen-prom.awk
	od -Ad -tu2 --endian=little -w2 -v $< | awk -f gen-prom.awk > $@

eeprom.bin: test.xml
	$(RM) $@
	$(SIITOOL) -m -o $@ $<

# Targets to analyze files
RxPDOSoft.o: RxPDOSoft.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
EEPROMContentPkg.o: EEPROMContentPkg.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
EEEmulPkg.o: EEEmulPkg.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
Lan9254Pkg.o: Lan9254Pkg.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
Lan9254ESCPkg.o: Lan9254ESCPkg.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
Lan9254ESC.o: Lan9254ESC.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
Lan9254Hbi.o: Lan9254Hbi.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
Lan9254HbiSoft.o: Lan9254HbiSoft.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
Lan9254ESCTb.o: Lan9254ESCTb.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
Lan9254ESCrun.o: Lan9254ESCrun.vhd
	$(GHDL) -a $(GHDLFLAGS) $<

# Files dependences
Lan9254ESC.o:  Lan9254Pkg.o Lan9254ESCPkg.o EEEmulPkg.o RxPDOSoft.o
EEEmulPkg.o: EEPROMContentPkg.o
Lan9254Hbi.o:  Lan9254Pkg.o
Lan9254HbiSoft.o:  Lan9254Pkg.o Lan9254Hbi.o
Lan9254ESCTb.o:  Lan9254Pkg.o Lan9254ESC.o Lan9254Hbi.o Lan9254HbiSoft.o
Lan9254ESCrun.o:  Lan9254Pkg.o Lan9254ESC.o Lan9254Hbi.o Lan9254Hbi.o

clean:
	$(RM) $(OBJS) $(PROG) dump.ghw work-*.cf e~$(PROG).o $(TOPS) EEPROMContentPkg.vhd

.PHONY: clean all run
