# Makefile automatically generated by ghdl
# Version: GHDL 0.36 (v0.36) [Dunoon edition] - GCC back-end code generator
# Command used to generate this makefile:
# ghdl --gen-makefile lan9254esctb

CROXX=
GHDL=$(CROSS)ghdl
CXX=$(CROSS)g++
GHDLFLAGS=

PROG=lan9254escrun
OBJS=Lan9254Pkg.o Lan9254ESC.o Lan9254Hbi.o Lan9254HbiSoft.o readWriteSim.o

TOPS=Lan9254ESCTb.o Lan9254ESCrun.o 

# Default target
all: $(PROG)

# Elaboration target
$(PROG): $(OBJS) $(TOPS)
	$(GHDL) -e -Wl,readWriteSim.o $(GHDLFLAGS) $@

readWriteSim.o: readWriteSim.c
	$(CXX) -c -o $@ $^ -Wall

# Run target
run: $(PROG)
	$(GHDL) -r $(PROG) $(GHDLRUNFLAGS)

# Targets to analyze files
Lan9254Pkg.o: Lan9254Pkg.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
Lan9254ESC.o: Lan9254ESC.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
Lan9254Hbi.o: Lan9254Hbi.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
Lan9254HbiSoft.o: Lan9254HbiSoft.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
Lan9254ESCTb.o: Lan9254ESCTb.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
Lan9254ESCrun.o: Lan9254ESCrun.vhd
	$(GHDL) -a $(GHDLFLAGS) $<

# Files dependences
Lan9254ESC.o:  Lan9254Pkg.o
Lan9254Hbi.o:  Lan9254Pkg.o
Lan9254HbiSoft.o:  Lan9254Pkg.o Lan9254Hbi.o
Lan9254ESCTb.o:  Lan9254Pkg.o Lan9254ESC.o Lan9254Hbi.o Lan9254HbiSoft.o
Lan9254ESCrun.o:  Lan9254Pkg.o Lan9254ESC.o Lan9254Hbi.o Lan9254Hbi.o

clean:
	$(RM) $(OBJS) $(PROG) dump.ghw work-*.cf e~$(PROG).o $(TOPS)

.PHONY: clean all run
