set ila_name hw_ila_1
if { [ info exists ::user_ila_name ] } {
  set ila_name $::user_ila_name
}

 create_hw_probe -map {probe0[15:0]} HBI.r.hbiOut.ad[15:0]  [get_hw_ilas ${ila_name}]
 create_hw_probe -map {probe0[17:16]} HBI.r.hbiOut.ale[1:0]  [get_hw_ilas ${ila_name}]
 create_hw_probe -map {probe0[19:18]} HBI.r.hbiOut.be[1:0]  [get_hw_ilas ${ila_name}]
 create_hw_probe -map {probe0[20]} HBI.r.hbiOut.rs  [get_hw_ilas ${ila_name}]
 create_hw_probe -map {probe0[21]} HBI.r.hbiOut.ws  [get_hw_ilas ${ila_name}]
 create_hw_probe -map {probe0[22]} HBI.r.hbiOut.cs  [get_hw_ilas ${ila_name}]
 create_hw_probe -map {probe0[23]} HBI.r.hbiOut.ad_t  [get_hw_ilas ${ila_name}]
 create_hw_probe -map {probe1[15:0]} HBI.hbiInp.ad[15:0]  [get_hw_ilas ${ila_name}]
 create_hw_probe -map {probe1[16]} HBI.hbiInp.waitAck  [get_hw_ilas ${ila_name}]
 create_hw_probe -map {probe1[17]} HBI.waitAckSync  [get_hw_ilas ${ila_name}]
 create_hw_probe -map {probe1[18]} HBI.dlyRun  [get_hw_ilas ${ila_name}]
 create_hw_probe -map {probe1[19]} HBI.tmoRun  [get_hw_ilas ${ila_name}]
 create_hw_probe -map {probe2[2:0]} HBI.r.state[2:0]  [get_hw_ilas ${ila_name}]
 create_hw_probe -map {probe2[3]} HBI.r.req.valid  [get_hw_ilas ${ila_name}]
 create_hw_probe -map {probe2[7:4]} HBI.r.req.be[3:0]  [get_hw_ilas ${ila_name}]
 create_hw_probe -map {probe2[8]} HBI.r.req.rdnwr  [get_hw_ilas ${ila_name}]
 create_hw_probe -map {probe2[9]} HBI.r.req.lock  [get_hw_ilas ${ila_name}]
 create_hw_probe -map {probe2[10]} HBI.r.req.noAck  [get_hw_ilas ${ila_name}]
 create_hw_probe -map {probe2[11]} HBI.r.rep.valid  [get_hw_ilas ${ila_name}]
 create_hw_probe -map {probe2[12:12]} HBI.r.rep.berr  [get_hw_ilas ${ila_name}]
 create_hw_probe -map {probe2[13]} HBI.rst  [get_hw_ilas ${ila_name}]
 create_hw_probe -map {probe2[14]} HBI.cen  [get_hw_ilas ${ila_name}]
 create_hw_probe -map {probe2[15]} HBI.req.valid  [get_hw_ilas ${ila_name}]
 create_hw_probe -map {probe2[19:16]} HBI.req.be[3:0]  [get_hw_ilas ${ila_name}]
 create_hw_probe -map {probe2[20]} HBI.req.rdnwr  [get_hw_ilas ${ila_name}]
 create_hw_probe -map {probe2[21]} HBI.req.lock  [get_hw_ilas ${ila_name}]
 create_hw_probe -map {probe2[22]} HBI.req.noAck  [get_hw_ilas ${ila_name}]
 create_hw_probe -map {probe2[63:32]} HBI.r.rep.rdata[31:0]  [get_hw_ilas ${ila_name}]
 create_hw_probe -map {probe3[15:0]} HBI.dbg1[15:0]  [get_hw_ilas ${ila_name}]
 create_hw_probe -map {probe3[31:16]} HBI.dbg2[15:0]  [get_hw_ilas ${ila_name}]
